(v3.7.2) - Ornstein-Uhlenbeck parameters range specification feature and workflows improvement (#465)
* Fix weather noise configuration in scripts/train_agent.py

* Environment: Env can accept ranges in OU parameters specification for each weather variable, update docstring

* Environment: Added weather variability specification checker

* Modeling: Detect ranges in OU parameters and select a random value before to start OU process

* Modeling: Save the exact OU configuration for each episode

* Documentation: Update copyright to 2025

* Documentation: Added information about ranges in OU parameters (environments section)

* Environment: Fix weather noise checker

* Tests: Fix some tau values in common and wrapper tests

* Test: Check creation of weather noise file configuration in modeling

* Tests: Added asserts for weather noise exceptions

* Add cov.xml to gitignore

* Documentation: Add test coverage section in tests chapter

* Fix docstring

* Update Sinergym version from 3.7.1 to 3.7.2

* Documentation: Add json file weather configuration information

* Workflow improvement: Setup Python before Poetry installation

* Workflow fix: Stop ussing github actions for autopep8 and isort. Instead, using the exact version of the project

diff --git a/.github/workflows/create_pr.yml b/.github/workflows/create_pr.yml
--- a/.github/workflows/create_pr.yml
+++ b/.github/workflows/create_pr.yml
@@ -4,7 +4,7 @@ on: pull_request
 # pwd: /home/runner/work/sinergym/sinergym
 
 jobs:
-  autopep8-check:
+  autopep8-isort-check:
     runs-on: ubuntu-24.04
     steps:
 
@@ -15,41 +15,6 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: ${{ vars.PYTHON_VERSION }}
-
-      - name: autopep8 check
-        id: autopep8
-        uses: peter-evans/autopep8@v2
-        with:
-          args: --exit-code --recursive --diff --aggressive --aggressive .
-
-      - name: Fail if autopep8 made changes
-        if: steps.autopep8.outputs.exit-code == 2
-        run: exit 1
-
-  isort-check:
-    runs-on: ubuntu-24.04
-    steps:
-
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ vars.PYTHON_VERSION }}
-
-      - name: isort check
-        id: isort-step
-        # default configuration use --check-only and --diff instead of --in-place options.
-        uses: isort/isort-action@master
-        continue-on-error: false
-
-  type-check:
-    runs-on: ubuntu-24.04
-    steps:
-
-      - name: Checkout code
-        uses: actions/checkout@v4
 
       - name: Install Poetry
         uses: snok/install-poetry@v1
@@ -58,11 +23,45 @@ jobs:
           virtualenvs-create: true
           virtualenvs-in-project: true
           installer-parallel: true
+          
+      - name: Install autopep8 and isort
+        run: poetry install --no-interaction --only format
+
+      - name: autopep8 check
+        id: autopep8
+        run: poetry run autopep8 --exit-code --recursive --diff --aggressive --aggressive .
+        continue-on-error: true
+
+      - name: isort check
+        id: isort
+        run: poetry run isort --check-only --diff .
+        continue-on-error: true
+
+      - name: Fail if autopep8/isort found diffs
+        if: steps.autopep8.outcome != 'success' || steps.isort.outcome != 'success'
+        run: |
+          echo "Error detected in code formatting (autopep8 and/or isort)."
+          exit 1
+
+  type-check:
+    runs-on: ubuntu-24.04
+    steps:
+
+      - name: Checkout code
+        uses: actions/checkout@v4
 
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-version: ${{ vars.PYTHON_VERSION }}
+
+      - name: Install Poetry
+        uses: snok/install-poetry@v1
+        with:
+          version: latest
+          virtualenvs-create: true
+          virtualenvs-in-project: true
+          installer-parallel: true
           
       - name: Install pytype
         run: poetry install --no-interaction --only typing
@@ -77,6 +76,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ vars.PYTHON_VERSION }}
+
       - name: Install Poetry
         uses: snok/install-poetry@v1
         with:
@@ -84,11 +88,6 @@ jobs:
           virtualenvs-create: true
           virtualenvs-in-project: true
           installer-parallel: true
-
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ vars.PYTHON_VERSION }}
       
       - name: Verify documentation update
         uses: dorny/paths-filter@v3
